var TREE_NODES = [
['TAIR', null, null,
["<span title=\"Information about the project, personnel, data in TAIR and how to link to TAIR.\">About TAIR</span>", null, null,
["<span title=\"Download bioinformatics software from TAIR.\">Get TAIR Software</span>", null, null,
["<span title=\"Java API for accessing AraCyc Arabidopsis Metabolic Pathway database\">Javacyc API for AraCyc</span>", '/tools/aracyc/javacyc', '_new'],
["<span title=\"Perl API for AraCyc and MetaCyc databases\">Perl API for AraCyc</span>", '/tools/perlcyc/', '_new'],
["<span title=\"Information about software written by TAIR programmers.\">About TAIR Software</span>", '/about/software.jsp', '_new'],
["<span title=\"Useful PERL scripts developed at TAIR\">TAIR Little Perl Scripts</span>", '/about/Perl_Scripts.jsp', '_new'],
["<span title=\"TAIR database schemas. Use the interactive entity relationship diagram viewer to see structure and attributes of TAIRs relational database.\">TAIR Schemas</span>", '/search/schemas.html', '_new'],
["<span title=\"Download TAIR's PatMatch Software to install on your computer.\">Download PatMatch Software </span>", 'ftp://ftp.arabidopsis.org/home/tair/Software/Patmatch', '_new'],
["<span title=\"Download VxInsight software and data files for analyzing clustered Arabidopsis Microarray data\">FTP site VxInsight software directory</span>", 'ftp://ftp.arabidopsis.org/home/tair/Software/VxInsight', '_new'],
],
["<span title=\"Announcements about features and data in TAIR database.\">TAIR News</span>", null, null,
["<span title=\"The latest news from TAIR\">TAIR News</span>", '/news/news.jsp', '_new'],
],
["<span title=\"Database usage and content statistics\">Database Statistics</span>", null, null,
["<span title=\"TAIR web usage statistics\">TAIR usage statistics</span>", '/usage/', '_new'],
],
["<span title=\"Disclaimer for TAIR database.\">Disclaimer</span>", '/disclaimer.jsp', '_new'],
["<span title=\"Announcement about the ABRC/TAIR collaboration.\">ABRC/TAIR release announcement</span>", '/abrc/abrcannounce.jsp', '_new'],
["<span title=\"What was new at TAIR. Past news releases.\">What Was New</span>", '/news/oldnews.jsp', '_new'],
["<span title=\"Instructions on how to link to TAIR detail pages from remote locations.\">Linking to TAIR</span>", '/about/linktotair.jsp', '_new'],
["<span title=\"TAIR database statistics. Updated list of current datatypes and size of current holdings.\">public table statistics</span>", '/jsp/tairjsp/pubDbStats.jsp', '_new'],
["<span title=\"Information about where we get our data from\">TAIR Data Sources</span>", '/about/datasources.jsp', '_new'],
["<span title=\"Introduction to the TAIR project. Who we are, what we do and how we do it.\">About the TAIR project</span>", '/about/index.jsp', '_new'],
["<span title=\"Email, phone and post contact information for TAIR.\">Contact TAIR</span>", '/contact/index.jsp', '_new'],
["<span title=\"Contact information for TAIR staff\">TAIR Staff</span>", '/about/staff.jsp', '_new'],
["<span title=\"How to cite TAIR database in publications\">Citing TAIR</span>", '/about/citingtair.jsp', '_new'],
["<span title=\"The original TAIR proposal on line. What WERE we thinking.\">TAIR proposal</span>", '/about/proposal.jsp', '_new'],
["<span title=\"TAIR database schemas. Use the interactive entity relationship diagram viewer to see structure and attributes of TAIRs relational database.\">TAIR Schemas</span>", '/search/schemas.html', '_new'],
["<span title=\"Papers published by TAIR curators and software developers\">TAIR publications</span>", '/about/tairpubs.jsp', '_new'],
["<span title=\"Whats on tap at TAIR!\">TAIR plans</span>", '/about/futureplans.jsp', '_new'],
],
["<span title=\"Where to find Arabidopsis mutants and sequence polymorphisms.\">Alleles,Polymorphisms and Phenotypes</span>", null, null,
["<span title=\"Find mutants, T-DNA/Transposon insertion lines, mapping populations and natural variants of Arabidopsis. Search by name, type, genotype,construct and more.\">Germplasm Search</span>", '/servlets/Search?action=new_search&type=germplasm', '_new'],
["<span title=\"Find mutant alleles, T-DNA and transposon insertions, transgenes, SNPs, INDELS and other polymorphisms. Search by name, type, location. Search can be limited to find polymorphisms for specific ecotypes.\">Polymorphism/Allele Search</span>", '/servlets/Search?action=new_search&type=polyallele', '_new'],
["<span title=\"Access to Monsanto's collection of Landsberg sequence and SNP/INDEL polymorphisms between Columbia and Landsberg (erecta) ecotypes.\">TAIR Monsanto SNP and Ler Sequence Collection</span>", '/Cereon/index.jsp', '_new'],
["<span title=\"Links to sources of seed stocks for finding mutants in your favorite genes. This includes sources not available from the major stock centers.\">List of Reverse Genetics Seed Stock Resources</span>", '/info/2010_projects/Reverse_Genetic_Stocks.jsp', '_new'],
],
["<span title=\"Find full length cDNAs, BAC clones, constructs and other ABRC stocks. Find and download amino acid and nucleotide sequences.\">Clones and Sequences</span>", null, null,
["<span title=\"Search for clones, vectors, libraries,pooled genomic DNA and filters. Find DNA Stocks to order from the ABRC.\">DNA Search</span>", '/servlets/Search?action=new_search&type=dna', '_new'],
["<span title=\"\">TAIR WU-BLAST 2.0 Form</span>", '/wublast/index2.jsp', '_new'],
["<span title=\"Access to Monsanto's collection of Landsberg sequence and SNP/INDEL polymorphisms between Columbia and Landsberg (erecta) ecotypes.\">TAIR Monsanto SNP and Ler Sequence Collection</span>", '/Cereon/index.jsp', '_new'],
["<span title=\"\">ESTs from MSU and CNRS</span>", '/abrc/ests.jsp', '_new'],
["<span title=\"\">Immature Seed ESTs donated to ABRC by Christoph Benning</span>", '/abrc/benningests.jsp', '_new'],
["<span title=\"\">ABRC Libraries and clones from libraries</span>", '/abrc/libraries.jsp', '_new'],
["<span title=\"\">Full length cDNA clones from the SSP Consortium.</span>", '/abrc/ssp_clone.jsp', '_new'],
["<span title=\"Information about Arabidopsis full length cDNA clones from RIKEN BioResource Center.\">RAFL Full Length cDNAs from RIKEN</span>", '/links/riken.jsp', '_new'],
["<span title=\"TAIR's version of NCBI BLAST similarity search tool. Input query sequences to search against customized datasets for Arabidopsis research.\">TAIR BLAST</span>", '/Blast/index.jsp', '_new'],
["<span title=\"Links to general nucleotide and protein sequence databases.\">Nucleotide and Protein Databases</span>", '/links/EST_search.jsp', '_new'],
["<span title=\"Access to Monsanto's Landsberg erecta sequence and SNP/INDEL polymorphism collection.\">TAIR Monsanto SNP and Ler Sequence Collection</span>", '/Cereon/index.html', '_new'],
],
["<span title=\"Download large and custom data files from TAIR's FTP site\">Download Data</span>", null, null,
["<span title=\"Download lists of genetic markers. Includes PCR primers for PCR based markers.\">Download Marker Data</span>", null, null,
["<span title=\"This file contains sequenced RI markers in fasta format with 	the RI marker name as the first word in the header.\">FTP site RI Markers</span>", 'ftp://ftp.arabidopsis.org/home/tair/Sequences/markers/RI_markers', '_new'],
["<span title=\"File containing lists of primer sequences for CAPS and SSLP Genetic Markers from TAIR database. The two primers for each marker are designated _A and _B.\">FTP site Genetic Marker Primer Pairs</span>", 'ftp://ftp.arabidopsis.org/home/tair/Sequences/markers/primers', '_new'],
],
["<span title=\"Download gene structural and functional annotations, EST mappings, gene family lists and more...\">Download Gene Data</span>", null, null,
["<span title=\"Folder containing downloadable data about genes.\">Gene Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Genes', '_new'],
],
["<span title=\"Download nuclear, chloroplast and mitochondrial sequences. Download TAIR's BLAST datasets.\">Download Sequences</span>", null, null,
["<span title=\"Obtain up to 1000 sequences at a time in FASTA or tab-delimited format. Download sequences or send them to the ClustalW multiple sequence alignment program at EBI.\">TAIR Bulk Sequence Download</span>", '/tools/bulk/sequences/index.jsp', '_new'],
["<span title=\"Folder containing TAIR BLAST dataset sequences in FASTA format.\">BLAST datasets Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Sequences/blast_datasets', '_new'],
["<span title=\"Sequences of mitochondrial chromosome and genes in FASTA format.\">FTP site Mitochondrial sequences folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Sequences/mitochondrial', '_new'],
["<span title=\"Fasta formatted files containing the complete psuedo-chromosome sequences of Arabidopsis. Each psuedo-chromosome file is defined by the chromosome number and release date.\">FTP site Whole Chromosomes Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Sequences/whole_chromosomes', '_new'],
["<span title=\"Older versions of fasta formatted complete sequences of Arabidopsis psuedo-chromosomes\">FTP site Old whole chromosome sequence folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Sequences/whole_chromosomes/OLD', '_new'],
],
["<span title=\"Download raw microarray data,mappings between microarray elements and AGI loci.\">Download Microarray Data</span>", null, null,
["<span title=\"Download raw microarray data, array element to gene mapping data, clustering software and more.\">Microarray Data Downloads</span>", 'ftp://ftp.arabidopsis.org/home/tair/Microarrays', '_new'],
],
['User Requested Data', null, null,
["<span title=\"FTP directory where data files requested by users is stored.\">FTP site User Requests</span>", 'ftp://ftp.arabidopsis.org/home/tair/User_Requests', '_new'],
["<span title=\"Old custom datasets requested by users\">Outdated data requests from users</span>", 'ftp://ftp.arabidopsis.org/home/tair/User_Requests/OLD', '_new'],
],
["<span title=\" FTP (file transfer protocol) site for downloading large or custom datasets.\">FTP Home directory</span>", 'ftp://ftp.arabidopsis.org/home/tair/home/tair', '_new'],
["<span title=\"Tab delimited lists of genes and corresponding GO annotations.\">Gene Ontology Annotation Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Genes/Gene_Ontology', '_new'],
["<span title=\"Folder containing tab delimited lists of gene families submitted by TAIR community.\">Gene Families Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Genes/Gene_families', '_new'],
["<span title=\"Tab delimited lists of update history for AGI loci.\">Locus History Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Genes/Locus_history', '_new'],
["<span title=\"Tab delimited text file containing history of new,deprecated, merged and split loci.\">Locus History</span>", 'ftp://ftp.arabidopsis.org/home/tair/Genes/Locus_history/locushistory.txt', '_new'],
["<span title=\"Map locations of markers and genotypes from Landsberg erecta X Cape Verdi Islands recombinant inbred map.\">Ler X Cvi RI data</span>", 'ftp://ftp.arabidopsis.org/home/tair/Maps/Ler_Cvi_RIdata', '_new'],
["<span title=\"FTP server for TAIR. Data files can be downloaded by anonymous FTP (file transfer protocol) to any personal computer.\">TAIR FTP site home directory</span>", 'ftp://ftp.arabidopsis.org/home/tair/home', '_new'],
],
["<span title=\"Web accessible software for analyzing sequences\">Data Analysis Tools</span>", null, null,
['Sequence Analysis Tools', null, null,
["<span title=\"This tool can be used to generate a restriction map for any sequence. Paste in the sequence and select enzymes. Map is displayed in a graphical and text format.\">TAIR Restriction Mapper</span>", '/cgi-bin/patmatch/RestrictionMapper.pl', '_new'],
["<span title=\"PatMatch is a tool for finding exact or degenerate matches to short amino acid or nucleotide sequences. It can be used to find domains, binding sites or any other single or repeat pattern. Search the entire genome or segments such as upstream or intergenic regions.\">Pattern Match</span>", '/cgi-bin/patmatch/nph-patmatch.pl', '_new'],
["<span title=\"Used to identify overrepresented 6-mers in nucleotide sequences. Can be used to identify potential cis-elements in upstream sequences. Upload a set of FASTA formatted sequences, such as upstream regions of co-expressed genes, and download a file of over-represented 6 mers.\">Motif Analysis</span>", '/tools/bulk/motiffinder/index.jsp', '_new'],
],
["<span title=\"Tools for predicting gene structures.\">Gene Structural Annotation Tools</span>", null, null,
["<span title=\"Links to gene prediction/annotation software.\">Gene Identification Programs</span>", '/links/gene_id.jsp', '_new'],
],
["<span title=\"Tools for finding similar proteins, conserved domains and motifs and protein families.\">Homologies,Domains and Motifs</span>", null, null,
["<span title=\"Obtain up to 1000 sequences at a time in FASTA or tab-delimited format. Download sequences or send them to the ClustalW multiple sequence alignment program at EBI.\">TAIR Bulk Sequence Download</span>", '/tools/bulk/sequences/index.jsp', '_new'],
["<span title=\"Links to external proteomics databases and tools for analyzing protein structure and function.\">Proteome Resources</span>", '/links/proteome.jsp', '_new'],
["<span title=\"PatMatch is a tool for finding exact or degenerate matches to short amino acid or nucleotide sequences. It can be used to find domains, binding sites or any other single or repeat pattern. Search the entire genome or segments such as upstream or intergenic regions.\">Pattern Match</span>", '/cgi-bin/patmatch/nph-patmatch.pl', '_new'],
["<span title=\"Lists of gene families compiled by experts and submitted to TAIR.\">TAIR Gene Family Information</span>", '/info/genefamily/genefamily.html', '_new'],
["<span title=\"Links to software for finding domains and motifs in nucleotide and protein sequences.\">Motif Analysis Tools</span>", '/links/motif_search.jsp', '_new'],
["<span title=\"Links to general protein structure databases and tools to predict protein structures.\">Protein Structure Databases and Search Tools</span>", '/links/prot_struct.jsp', '_new'],
["<span title=\"Links to web based multi-functional sequence analysis tools. These resources generally encompass a suite of software including multiple database searching,similarity searching, multiple sequence alignment and phylogenetic analysis.\">Comprehensive Sequence Analysis Tools and Resources</span>", '/links/seq_resources.jsp', '_new'],
],
["<span title=\"Web tools for finding similar sequences.\">Sequence Similarity Tools</span>", null, null,
["<span title=\"\">TAIR WU-BLAST 2.0 Form</span>", '/wublast/index2.jsp', '_new'],
["<span title=\"TAIR's version of NCBI BLAST similarity search tool. Input query sequences to search against customized datasets for Arabidopsis research.\">TAIR BLAST</span>", '/Blast/index.jsp', '_new'],
["<span title=\"Links to pairwise similarity searching software.\">Overall Pairwise Similarity Searches</span>", '/links/sim_search.jsp', '_new'],
],
["<span title=\"TAIR's collection of software for structural and functional analysis of Arabidopsis genes.\">TAIR Tools</span>", '/tools/index.jsp', '_new'],
],
["<span title=\"Resources for teaching and learning about Arabidopsis, plant biology, genetics and genomics.\">Education</span>", null, null,
["<span title=\"Information about the biology and history of Arabidopsis thaliana\">About Arabidopsis</span>", null, null,
["<span title=\"Information about the AGI genome sequencing effort\">Genome Sequencing</span>", null, null,
["<span title=\"Information about the Arabidopsis Genome Initiative project which sequenced the genome in 2000.\">TAIR AGI Information</span>", '/info/agi.jsp', '_new'],
["<span title=\"Status of the Arabidopsis genome sequencing initiative.\">Genome Update</span>", '/info/agicomplete.jsp', '_new'],
["<span title=\"Announcement regarding the release of the Arabidopsis genome sequence in 2000.\">TAIR Genome Sequence Release</span>", '/info/genome_release.jsp', '_new'],
],
["<span title=\"Links to pages of information about Arabidopsis research, resources and history.\">Information about Arabidopsis</span>", '/info/index.jsp', '_new'],
["<span title=\"Information about Arabidopsis, its history and use as a research organism.\">Arabidopsis History,taxonomy and life cycle</span>", '/info/aboutarabidopsis.jsp', '_new'],
["<span title=\"Descriptions of Arabidopsis growth stages from Boyes et al., Plant Cell (2001)\">Arabidopsis Growth Stages</span>", '/info/growth.jsp', '_new'],
],
["<span title=\"Links to science education resources for scientists, educators and students.\">TAIR Education/Outreach</span>", '/info/education.jsp', '_new'],
["<span title=\"Listings and descriptions of science education and outreach programs.\">Science Education and Outreach Programs</span>", '/info/programs.jsp', '_new'],
["<span title=\"Information about the NSF broader impacts merit review criteria and science education for researchers.\">Science Education and Outreach Guide for Scientists</span>", '/info/outreach2.jsp', '_new'],
["<span title=\"Links to educational websites and resources for plant biology education targeted to students and teachers.\">Resources for Educators and Students</span>", '/info/teach.jsp', '_new'],
["<span title=\"Presentation and notes from an informal meeting of scientists, educators and education specialists on plant biology education.\">Proceedings of Plant Biology, Genomics and Genetics researchers and educators meeting </span>", '/info/bmeeting.jsp', '_new'],
["<span title=\"On line resources for plant biology education.\">Educational web sites</span>", '/info/online.jsp', '_new'],
["<span title=\"Links to newsgroups for plant biology educators\">Plant Biology education newsgroups</span>", '/info/email.jsp', '_new'],
],
["<span title=\"Links to useful resources from other databases and websites.\">External Links</span>", null, null,
["<span title=\"Find web-accessible bioinformatics software and software to download\">Bioinformatics software</span>", null, null,
["<span title=\"Download software for linkage analysis and SNP mapping\">Genetic Mapping Software</span>", null, null,
["<span title=\"This software generates probability plots and genotype displays. It requires MATLAB v4.2 or higher, which is available for all common computing platforms. Contact MathWorks (www.mathworks.com) for ordering details.\">FTP site Intermap Software folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Software/Intermap', '_new'],
],
["<span title=\"Links to computer software and programming languages for bioinformatics. \">Bioinformatics Resources on the Web</span>", '/links/bioinformatics.jsp', '_new'],
["<span title=\"Directory of software available for downloading from TAIR's FTP site.\">FTP site Software Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Software', '_new'],
["<span title=\"This folder contains supplementary data for Nordborg et al, 2002. The extent of linkage disequilibrium in Arabidopsis thaliana\">FTP site Linkage Disequilibrium mapping data download</span>", 'ftp://ftp.arabidopsis.org/home/tair/Software/Linkage_disequilibrium', '_new'],
],
["<span title=\"Links to other websites of interest to Arabidopsis Researchers.\">TAIR External Links</span>", '/links/index.jsp', '_new'],
["<span title=\"Find Arabidopsis stock centers, service facilities and databases\">TAIR Arabidopsis Links</span>", '/links/atlinks.jsp', '_new'],
["<span title=\"Standards for gene and gene family nomenclature in other species.\">Nomenclature resources</span>", '/links/nomenclature.jsp', '_new'],
["<span title=\"Links to external databases and sequence analysis tools\">Sequence Analysis Resources</span>", '/links/webtools.jsp', '_new'],
["<span title=\"Links to external plant and animal genome databases.\">TAIR Genome Databases</span>", '/links/genomedbs.jsp', '_new'],
["<span title=\"Links to external proteomics databases and tools for analyzing protein structure and function.\">Proteome Resources</span>", '/links/proteome.jsp', '_new'],
["<span title=\"Links to external resources for finding and analyzing cis-regulatory elements\">Cis-element Resources</span>", '/links/cis_element.jsp', '_new'],
["<span title=\"Links to external gene expression databases and software for analyzing gene expression data.\">Links Microarray Databases and Analysis Tools</span>", '/links/microarrays.jsp', '_new'],
["<span title=\"Links to plant databases and digital libraries.\">TAIR Plant Biology Links</span>", '/links/plantresources.jsp', '_new'],
["<span title=\"Links to computer software and programming languages for bioinformatics. \">Bioinformatics Resources on the Web</span>", '/links/bioinformatics.jsp', '_new'],
["<span title=\"Links to general nucleotide and protein sequence databases.\">Nucleotide and Protein Databases</span>", '/links/EST_search.jsp', '_new'],
["<span title=\"Links to pairwise similarity searching software.\">Overall Pairwise Similarity Searches</span>", '/links/sim_search.jsp', '_new'],
["<span title=\"Links to gene prediction/annotation software.\">Gene Identification Programs</span>", '/links/gene_id.jsp', '_new'],
["<span title=\"Links to software for finding domains and motifs in nucleotide and protein sequences.\">Motif Analysis Tools</span>", '/links/motif_search.jsp', '_new'],
["<span title=\"Links to general protein structure databases and tools to predict protein structures.\">Protein Structure Databases and Search Tools</span>", '/links/prot_struct.jsp', '_new'],
["<span title=\"Links to web based multi-functional sequence analysis tools. These resources generally encompass a suite of software including multiple database searching,similarity searching, multiple sequence alignment and phylogenetic analysis.\">Comprehensive Sequence Analysis Tools and Resources</span>", '/links/seq_resources.jsp', '_new'],
["<span title=\"Links to software for designing PCR primers for DNA amplification and sequencing.\">PCR Primer Design Programs</span>", '/links/pcr.jsp', '_new'],
],
["<span title=\"Tools for finding and analyzing Arabidopsis microarray data. Find information about gene expression in Arabidopsis.\">Gene Expression Resources</span>", null, null,
["<span title=\"How to submit microarray data to TAIR database\">Guidelines for Submitting Microarray Data</span>", '/submit/microarray.submission.jsp', '_new'],
["<span title=\"Links to Arabidopsis microarray resources including information about array designs, sources of chips, microarray facilities and Arabidopsis microarray projects.\">Information about Arabidopsis Microarray Experiments and Resources.</span>", '/info/expression/index.jsp', '_new'],
["<span title=\"Find genes, annotations, publications and microarray experiments by keyword. Browse the ontologies to find groups of similar genes, etc...\">Keyword Search and Browse</span>", '/servlets/Search?action=new_search&type=keyword', '_new'],
["<span title=\"Use for functional classification of Arabidopsis genes. Upload a list of AGI locus identifiers and obtain a list of Gene Ontology associations. Or classify genes into broad categories and display as a list or show distribution in pie chart format.\">TAIR GO Annotation Search and Analysis</span>", '/tools/bulk/go/index.jsp', '_new'],
["<span title=\"Find what genes are arrayed on AFGC and Affymetrix chips. View spot history for AFGC array elements and clustered data from across all AFGC experiments. Download lists of mappings between genes and array elements.\">Microarray Elements Search and Download</span>", '/tools/bulk/microarray/index.jsp', '_new'],
["<span title=\"Find and Download Data from Arabidopsis microarray experiments. Search by keywords, experiment name and researcher name.\">Microarray Experiments Search</span>", '/servlets/Search?type=expr&search_action=new_search', '_new'],
["<span title=\"Find expression data for a gene or set of genes using locus identifiers or microarray element names. Select cut off values for expression or limit to only specific array technologies.\">Expression Search</span>", '/servlets/Search?action=new_search&type=expression', '_new'],
["<span title=\"Links to external resources for finding and analyzing cis-regulatory elements\">Cis-element Resources</span>", '/links/cis_element.jsp', '_new'],
["<span title=\"Links to external gene expression databases and software for analyzing gene expression data.\">Links Microarray Databases and Analysis Tools</span>", '/links/microarrays.jsp', '_new'],
["<span title=\"Used to identify overrepresented 6-mers in nucleotide sequences. Can be used to identify potential cis-elements in upstream sequences. Upload a set of FASTA formatted sequences, such as upstream regions of co-expressed genes, and download a file of over-represented 6 mers.\">Motif Analysis</span>", '/tools/bulk/motiffinder/index.jsp', '_new'],
["<span title=\"VxInsight can be used to analyze Arabidopsis microarray data. It uses predefined, clustered datasets from TAIR's archive of Arabidopsis microarray experiments. The intuitive interface displays clusters as mountains which can be interrogated down to the single element level. Cluster data can be queried by name, GO term,metabolic pathway and sets of genes can be downloaded along with their annotations, in tab-delimited format. Software requires a PC and must be downloaded, along with the datasets, to a personal computer.\">Vx Insight</span>", '/tools/bulk/microarray/analysis/index.jsp#vx', '_new'],
["<span title=\"A Java-based software for visualizing microarray gene expression data in a hierarchical tree view. The software must be downloaded along with the datasets onto a personal computer (PC or MAC). The datasets are analyzed, clustered microarray data from TAIR.\">Java Tree View</span>", '/tools/bulk/microarray/analysis/index.jsp#jtv', '_new'],
["<span title=\"\">Cold Spring Harbor Enhancer Trap and Gene Trap Lines</span>", '/abrc/cshl_gtet.jsp', '_new'],
["<span title=\"\">Enhancer Trap Lines from Scott Poethig</span>", '/abrc/poethig.jsp', '_new'],
["<span title=\"Find microarray experiment data in TAIR and download raw data.\">Microarray Expression Search</span>", '/jsp/search/expression_form.jsp', '_new'],
["<span title=\"Browse or search using keywords to find genes, microarray experiments,papers and annotations.\">Keyword Search and Browse</span>", '/jsp/search/keyword_form.jsp', '_new'],
["<span title=\"Guidelines and submission forms for submitting microarray experiment data to TAIR.\">Guidelines for Submitting Microarray Experiment Data</span>", '/info/microarray_experiment.jsp', '_new'],
["<span title=\"Guidelines and submission forms for submitting data about array designs (chip information) to TAIR.\">Array Design Submission</span>", '/submit/array_submission.jsp', '_new'],
["<span title=\"Links to software for finding domains and motifs in nucleotide and protein sequences.\">Motif Analysis Tools</span>", '/links/motif_search.jsp', '_new'],
["<span title=\"\">GFP lines from Jim Haseloff</span>", '/abrc/haseloff.jsp', '_new'],
["<span title=\"\">Promoter Trap lines from Patrick Gallois</span>", '/abrc/gallois.jsp', '_new'],
["<span title=\"Random GFP cDNA fusion transformants for sub cellular protein localization.\">Random GFP cDNA Fusion T-DNA Transformants from David Ehrhardt</span>", '/abrc/ehrhardt_gfp.jsp', '_new'],
["<span title=\"Download VxInsight software and data files for analyzing clustered Arabidopsis Microarray data\">FTP site VxInsight software directory</span>", 'ftp://ftp.arabidopsis.org/home/tair/Software/VxInsight', '_new'],
["<span title=\"List of micorarray experiments from AtGenExpress\">AtGenExpress</span>", '/info/expression/ATGenExpress.jsp', '_new'],
],
["<span title=\"Tools for finding and analyzing Arabidopsis genes.\">Gene Resources</span>", null, null,
["<span title=\"Find and analyze protein domains, motifs and families.\">Homologies,Domains and Motifs</span>", null, null,
["<span title=\"Obtain up to 1000 sequences at a time in FASTA or tab-delimited format. Download sequences or send them to the ClustalW multiple sequence alignment program at EBI.\">TAIR Bulk Sequence Download</span>", '/tools/bulk/sequences/index.jsp', '_new'],
["<span title=\"Links to external proteomics databases and tools for analyzing protein structure and function.\">Proteome Resources</span>", '/links/proteome.jsp', '_new'],
["<span title=\"PatMatch is a tool for finding exact or degenerate matches to short amino acid or nucleotide sequences. It can be used to find domains, binding sites or any other single or repeat pattern. Search the entire genome or segments such as upstream or intergenic regions.\">Pattern Match</span>", '/cgi-bin/patmatch/nph-patmatch.pl', '_new'],
["<span title=\"Lists of gene families compiled by experts and submitted to TAIR.\">TAIR Gene Family Information</span>", '/info/genefamily/genefamily.html', '_new'],
["<span title=\"Links to software for finding domains and motifs in nucleotide and protein sequences.\">Motif Analysis Tools</span>", '/links/motif_search.jsp', '_new'],
["<span title=\"Links to general protein structure databases and tools to predict protein structures.\">Protein Structure Databases and Search Tools</span>", '/links/prot_struct.jsp', '_new'],
["<span title=\"Links to web based multi-functional sequence analysis tools. These resources generally encompass a suite of software including multiple database searching,similarity searching, multiple sequence alignment and phylogenetic analysis.\">Comprehensive Sequence Analysis Tools and Resources</span>", '/links/seq_resources.jsp', '_new'],
],
["<span title=\"Information about naming genes based on sequence similarity or mutant phenotype. Arabidopsis nomenclature standards and guidelines\">Gene Nomenclature</span>", null, null,
["<span title=\"Standards for gene and gene family nomenclature in other species.\">Nomenclature resources</span>", '/links/nomenclature.jsp', '_new'],
["<span title=\"Guidelines for gene naming in Arabidopsis.\">Arabidopsis nomenclature</span>", '/info/guidelines.jsp', '_new'],
["<span title=\"Naming conventions used by TIGR gene annotators.\">TIGR Arabidopsis Gene Nomenclature</span>", '/info/tigr_naming.jsp', '_new'],
["<span title=\"Guidelines and conventions for naming mutant genes.\">Mutant Gene Nomenclature</span>", '/info/namerule.jsp', '_new'],
],
["<span title=\"TAIR's Arabidopsis genome browser. View genes, polymorphisms, T-DNA/transposon insertions, tiling path clones, transcripts, genetic markers, full length cDNAs in whole genome context.\">Sequence Viewer</span>", '/servlets/sv', '_new'],
["<span title=\"Gene family lists contributed by TAIR community experts\">Arabidopsis Gene Families</span>", '/info/genefamily/genefamily.html', '_new'],
["<span title=\"Find genes by name, keyword,type and location.\">Gene Search</span>", '/servlets/Search?type=gene&action=new_search', '_new'],
["<span title=\"Find genes, annotations, publications and microarray experiments by keyword. Browse the ontologies to find groups of similar genes, etc...\">Keyword Search and Browse</span>", '/servlets/Search?action=new_search&type=keyword', '_new'],
["<span title=\"Use for functional classification of Arabidopsis genes. Upload a list of AGI locus identifiers and obtain a list of Gene Ontology associations. Or classify genes into broad categories and display as a list or show distribution in pie chart format.\">TAIR GO Annotation Search and Analysis</span>", '/tools/bulk/go/index.jsp', '_new'],
["<span title=\"Find the history of revisions such as splits and merges of genes. Upload a file, type or paste in AGI locus identifiers and obtain a downloadable list of all changes made to each locus.\">Locus History Search</span>", '/tools/bulk/locushistory/index.jsp', '_new'],
["<span title=\"Used as a meta search agent to find information about genes from multiple databases. Search TAIR, TIGR,NASC,PubMED,NCBI and PIR for information about your favorite gene.\">Gene Hunter</span>", '/cgi-bin/geneform/geneform.pl', '_new'],
["<span title=\"Information about ontologies used by TAIR curators to describe biological data.\">TAIR Ontologies</span>", '/info/ontologies/', '_new'],
["<span title=\"Browse or search using keywords to find genes, microarray experiments,papers and annotations.\">Keyword Search and Browse</span>", '/jsp/search/keyword_form.jsp', '_new'],
["<span title=\"Information how to access and use controlled vocabulary annotations at TAIR\">TAIR Ontologies</span>", '/info/ontologies', '_new'],
["<span title=\"Links to gene prediction/annotation software.\">Gene Identification Programs</span>", '/links/gene_id.jsp', '_new'],
],
["<span title=\"Find markers, maps and strains for positional cloning of Arabidopsis genes.\">Genetic Markers, Maps and Mapping Strains</span>", null, null,
["<span title=\"Draw maps showing the location of genes on all 5 chromosomes\">Chromosome Map Tool</span>", '/jsp/ChromosomeMap/tool.jsp', '_new'],
["<span title=\"TAIR's Arabidopsis genome browser. View genes, polymorphisms, T-DNA/transposon insertions, tiling path clones, transcripts, genetic markers, full length cDNAs in whole genome context.\">Sequence Viewer</span>", '/servlets/sv', '_new'],
["<span title=\"View, align and compare genetic, sequence and physical maps.\">MapViewer</span>", '/servlets/mapper', '_new'],
["<span title=\"Find genetic markers for mapping or following linked genes. Search by name,type, and location. Can be used to find markers polymorphic between selected ecotypes.\">Genetic Marker Search</span>", '/servlets/Search?type=marker&action=new_search', '_new'],
["<span title=\"Find mutants, T-DNA/Transposon insertion lines, mapping populations and natural variants of Arabidopsis. Search by name, type, genotype,construct and more.\">Germplasm Search</span>", '/servlets/Search?action=new_search&type=germplasm', '_new'],
["<span title=\"Find natural variants of Arabidopsis and other species. Search by name, stock number and collection site data such as country.\">Ecotype Search</span>", '/servlets/Search?action=new_search&type=ecotype', '_new'],
["<span title=\"Find mutant alleles, T-DNA and transposon insertions, transgenes, SNPs, INDELS and other polymorphisms. Search by name, type, location. Search can be limited to find polymorphisms for specific ecotypes.\">Polymorphism/Allele Search</span>", '/servlets/Search?action=new_search&type=polyallele', '_new'],
["<span title=\"Used to align and compare different map types for the same chromosome. Align genetic and sequence based maps to find genes within a defined genetic interval.\">TAIR Map Viewer</span>", '/servlets/mapper', '_new'],
["<span title=\"Upload or paste in a set of locus identifiers to paint a custom map of genes showing locations on all 5 chromosomes.\">TAIR Chromosome Map Utility</span>", '/jsp/ChromosomeMap/tool.jsp', '_new'],
["<span title=\"\">Recombinant inbred mapping lines from ABRC</span>", '/abrc/ri_mapping.jsp', '_new'],
["<span title=\"Access to Monsanto's Landsberg erecta sequence and SNP/INDEL polymorphism collection.\">TAIR Monsanto SNP and Ler Sequence Collection</span>", '/Cereon/index.html', '_new'],
["<span title=\"Launch pad lines for transposon tagging in Arabidopsis\">Ds Launch Pad lines from P. Muskett</span>", '/abrc/muskett_launchpad.jsp', '_new'],
["<span title=\"Col X Ler recombinant inbred population\">Recombinant Inbred lines from C. Lister and C. Dean</span>", '/abrc/dean_ri.jsp', '_new'],
["<span title=\"Ler X CVi recombinant inbred population\">Recombinant Inbred Lines from M. Koornneef and C. Alonso-Blanco</span>", '/abrc/koornneef_ri.jsp', '_new'],
["<span title=\"Col-3 or Col-5 X Nd-1 recombinant inbred population\">RI lines donated by E. Holub, J. Beynon and I. Crute</span>", '/abrc/holub_beynon_crute.jsp', '_new'],
["<span title=\"ColXKas-1 recombinant inbred population\">Recombinant Inbred Lines from S. Somerville</span>", '/abrc/somerville_ri.jsp', '_new'],
["<span title=\"Bay-0 x Shahdara recombinant inbred population.\">Recombinant Inbred lines from Loudet and Chaillou.</span>", '/abrc/Loudet_Chaillou_ri.jsp', '_new'],
["<span title=\"Mapping population with dominant T-DNA linked markers.\">Marker Lines with Mapped T-DNA Insertions from Dr. Mieke van Lijsebettens</span>", '/abrc/vanlijsebettens.jsp', '_new'],
["<span title=\"L(er)X Col mapping population in qrt mutant background for tetrad analysis.\">Tetrad Mapping Population donated by D. Preuss and G. Copenhaver</span>", '/abrc/preuss.jsp', '_new'],
],
["<span title=\"Search and browse the annotated Arabidopsis genome.\">Genome Browser</span>", null, null,
["<span title=\"TAIR's Arabidopsis genome browser. View genes, polymorphisms, T-DNA/transposon insertions, tiling path clones, transcripts, genetic markers, full length cDNAs in whole genome context.\">Sequence Viewer</span>", '/servlets/sv', '_new'],
["<span title=\"View, align and compare genetic, sequence and physical maps.\">MapViewer</span>", '/servlets/mapper', '_new'],
],
["<span title=\"Help pages for using TAIR database, Glossary of terms and Frequently Asked Questions.\">Help</span>", null, null,
["<span title=\"Help for using the Pathway Tools\">About the Pathway Tools Web server</span>", '/ecocyc/help.jsp', '_new'],
["<span title=\"Glossary of terms used in TAIR\">Glossary</span>", '/servlets/processor?type=definition&update_action=glossary', '_new'],
["<span title=\"\">TAIR Help Updating Publications</span>", '/help/helppages/addpub.jsp', '_new'],
["<span title=\"How to use the protocol search and understand the results.\">Protocol Search Help</span>", '/help/helppages/protsearch_help.jsp', '_new'],
["<span title=\"Understanding and using the plant GO slim for functional classification of Arabidopsis geness.\">GO Slim Help</span>", '/help/helppages/go_slim_help.jsp', '_new'],
["<span title=\"Helpful documents about using TAIR database and tools.\">TAIR Help Central</span>", '/help/index.jsp', '_new'],
["<span title=\"How to use TAIR's Bulk Sequence Download and Analysis Tool.\">Using TAIR Bulk Sequence Download and Analysis Tool</span>", '/help/helppages/bulkseqhelp.jsp', '_new'],
["<span title=\"How to use TAIR's Bulk GO annotation download and Analysis tool\">TAIR Help Bulk GO Annotation Download and Analysis</span>", '/help/helppages/bulkgohelp.jsp', '_new'],
["<span title=\"How to use TAIR's locus history search tool.\">TAIR Locus History Search</span>", '/help/helppages/locushistoryhelp.jsp', '_new'],
["<span title=\"How to use TAIR's Microarray element search.\">TAIR help Microarray Element Search</span>", '/help/helppages/microarray_readme.jsp', '_new'],
["<span title=\"Information how to access and use controlled vocabulary annotations at TAIR\">TAIR Ontologies</span>", '/info/ontologies', '_new'],
["<span title=\"Instructions for how to use the SeqViewer Genome Search and Browse tool.\">SeqViewer Introduction</span>", '/seqViewer/help/sv_intro.jsp', '_new'],
["<span title=\"Help for accessing and using the Monsanto Arabidopsis polymorphism collection.\">TAIR Monsanto Arabidopsis Polymorphisms Help</span>", '/Cereon/help.jsp', '_new'],
["<span title=\"Help documents for accessing and using the Monsanto Landsberg erecta sequences.\">Monsanto Arabidopsis Landsberg Sequence Help</span>", '/Cereon/help_seq.jsp', '_new'],
["<span title=\"TAIRs list of frequently asked questions and answers.\">TAIR FAQ</span>", '/help/faq.jsp', '_new'],
["<span title=\"A brief guide to TAIR for new users.\">TAIR Quickstart</span>", '/help/quickstart.jsp', '_new'],
["<span title=\"Help documents for how to use TAIR database searches, understand detail pages, analysis tools and registration and profile maintenance.\">TAIR Database and Tool Help</span>", '/help/helpcontents.jsp', '_new'],
["<span title=\"Searchable archive of curators responses to user's questions.\">TAIR Help archive</span>", '/help/questions.jsp', '_new'],
["<span title=\"Help for using TAIR expression viewer\">Expression Viewer Help</span>", '/help/helppages/help_expression.jsp', '_new'],
["<span title=\"\">TAIR help Microarray Expression Search</span>", '/help/helppages/expression_search.jsp', '_new'],
["<span title=\"\">TAIR Protein Search Help</span>", '/help/helppages/proteinhelp.jsp', '_new'],
["<span title=\"\">TAIR Help Keyword Search</span>", '/help/helppages/keyser.jsp', '_new'],
["<span title=\"\">TAIR Help Keyword Browser</span>", '/help/helppages/keybrowse.jsp', '_new'],
["<span title=\"TAIR MapViewer help\">tairmaps.htm</span>", '/mapViewer/help/tairmaps.jsp', '_new'],
["<span title=\"\">TAIR help Community Registration</span>", '/help/helppages/commreg.jsp', '_new'],
["<span title=\"\">TAIR Help Adding Comments</span>", '/help/helppages/addcomment.jsp', '_new'],
["<span title=\"Help navigating TAIR\">TAIR navigation</span>", '/help/helppages/tairseaa.jsp', '_new'],
["<span title=\"Help using TAIR general search.\">TAIR help basics</span>", '/help/helppages/initials.jsp', '_new'],
["<span title=\"How to use TAIR marker search\">TAIR Help Marker Search</span>", '/help/helppages/markerse.jsp', '_new'],
["<span title=\"How to use TAIRs DNA search\">TAIR Help DNA Search</span>", '/help/helppages/dnasearch.jsp', '_new'],
["<span title=\"How to use TAIRs polymorphism search to find SNPs, INDELS,insertions and alleles.\">Using the Polymorphism/Allele Search</span>", '/help/helppages/polyser.jsp', '_new'],
["<span title=\"How to use TAIRs germplasm search to find seed stocks including insertion lines, mutants, ecotypes and recombinant inbred lines.\">TAIR Help Germplasm Search</span>", '/help/helppages/germsearch.jsp', '_new'],
["<span title=\"How to use TAIRs ecotype search to find natural variants (ecotypes) of Arabidopsis from around the world. Search by name, stock number, location and more.\">TAIR Help Ecotype Search</span>", '/help/helppages/ecosearch.jsp', '_new'],
["<span title=\"\">TAIR Publication Search Help</span>", '/help/helppages/publicsearch.jsp', '_new'],
["<span title=\"\">TAIR Help Protein Search</span>", '/help/helppages/prosearch.jsp', '_new'],
["<span title=\"\">TAIR help Community Search</span>", '/help/helppages/commsearch.jsp', '_new'],
["<span title=\"\">TAIR help Affiliations</span>", '/help/helppages/affiliate.jsp', '_new'],
["<span title=\"\">TAIR help Adding Labs</span>", '/help/helppages/addlab.jsp', '_new'],
["<span title=\"\">TAIR help Adding Organizations</span>", '/help/helppages/addorg.jsp', '_new'],
["<span title=\"How to use TAIR's MapViewer tool\">Map Viewer Help Documents</span>", '/mapViewer/help/tairmapa.jsp', '_new'],
["<span title=\"How to use NCBI BLAST at TAIR\">TAIR Help Using BLAST</span>", '/help/helppages/BLAST_help.jsp', '_new'],
["<span title=\"\">TAIR help Understanding BLAST results</span>", '/help/helppages/Blastresults.jsp', '_new'],
["<span title=\"Understanding how to use BLAST settings\">BLAST Options and Defaults</span>", '/help/helppages/BLASToptions.jsp', '_new'],
["<span title=\"Help documentation for Motif Finder\">Motif Finder Help</span>", '/help/helppages/motif_help.jsp', '_new'],
["<span title=\"Help documentation Using the Microarray Experiment Search.\">Microarray Experiment Search Help</span>", '/help/helppages/exper_search.jsp', '_new'],
["<span title=\"Help for understanding and using the microarray experiment search results.\">Microarray Experiment Results Help</span>", '/help/helppages/exper_result.jsp', '_new'],
["<span title=\"Help using and understanding the microarray experiment detail pages.\">Microarray Experiment Detail Page Help</span>", '/help/helppages/exper_detail.jsp', '_new'],
["<span title=\"Explains the Gene Ontology and how to find and use Arabidopsis GO annotations.\">Gene Ontology Tutorial</span>", '/help/tutorials/go_intro.jsp', '_new'],
],
["<span title=\"Links to websites and databases for finding Arabidopsis mutants.\">Knockouts,Transgenics and other Mutation Resources</span>", null, null,
["<span title=\"Find mutants, T-DNA/Transposon insertion lines, mapping populations and natural variants of Arabidopsis. Search by name, type, genotype,construct and more.\">Germplasm Search</span>", '/servlets/Search?action=new_search&type=germplasm', '_new'],
["<span title=\"Find mutant alleles, T-DNA and transposon insertions, transgenes, SNPs, INDELS and other polymorphisms. Search by name, type, location. Search can be limited to find polymorphisms for specific ecotypes.\">Polymorphism/Allele Search</span>", '/servlets/Search?action=new_search&type=polyallele', '_new'],
["<span title=\"Links to sources of gene knockouts, point mutations and tools for targeted mutagenesis.\">Knockouts,Insertions and Mutation Resources</span>", '/links/insertion.jsp', '_new'],
["<span title=\"Information about Salk T-DNA insertion line stocks.\">Sequence-indexed T-DNA Lines donated by J. Ecker</span>", '/abrc/ecker_flank.jsp', '_new'],
["<span title=\"\">Cold Spring Harbor Enhancer Trap and Gene Trap Lines</span>", '/abrc/cshl_gtet.jsp', '_new'],
["<span title=\"\">T-DNA Seed Pools and Lines available at ABRC</span>", '/abrc/tdna_lines.jsp', '_new'],
["<span title=\"T-DNA insertion lines from the Arabidopsis Knockout Facility\">AKF seed pools donated to ABRC</span>", '/abrc/akf.jsp', '_new'],
["<span title=\"Ds transposon insertion lines from the Institute for Molecular Agrobiology.\">Institute for Molecular Agrobiology (IMA)lines donated to ABRC</span>", '/abrc/ima.jsp', '_new'],
["<span title=\"How to obtain Targeted Local Induced Lesion lines.\">Tilling lines from Henikoff and Comai labs</span>", '/abrc/henikoff.jsp', '_new'],
["<span title=\"\">Enhancer Trap Lines from Scott Poethig</span>", '/abrc/poethig.jsp', '_new'],
["<span title=\"Information about how T-DNA lines donated by Ken Feldmann were generated and how to order them from ABRC.\">T-DNA lines from Ken Feldmann</span>", '/abrc/feldmann.jsp', '_new'],
["<span title=\"Information about how to order T-DNA lines donated by Tom Jack and how they were generated.\">T-DNA lines from T. Jack</span>", '/abrc/jack.jsp', '_new'],
["<span title=\"How to order T-DNA lines from INRA and how they were made.\">T-DNA lines from INRA</span>", '/abrc/inra.jsp', '_new'],
["<span title=\"How to order T-DNA lines donate by Detlef Weigel and how they were generated.\">T-DNA lines from Detlef Weigel</span>", '/abrc/weigel.jsp', '_new'],
["<span title=\"How to order T-DNA lines from Alonso and Crosby and how they were generated.\">T-DNA Transformed Lines donated by J. Alonso, W. Crosby and</span>", '/abrc/alonso.jsp', '_new'],
["<span title=\"How to order activation tag lines from Scheible and Somerville and how they were generated.\">T-DNA Transformed Activation Tag lines from W. Scheible and C. Somerville</span>", '/abrc/Scheible.jsp', '_new'],
["<span title=\"How to order T-DNA insertion lines donated by Sussman and Amasino and how they were generated.\">T-DNA lines from M. Sussman and R. Amasino</span>", '/abrc/sussman_fwd.jsp', '_new'],
["<span title=\"\">T-DNA lines from R. Bressan and S. Yokoi</span>", '/abrc/bressan.jsp', '_new'],
["<span title=\"\">T-DNA Lines donated by S. LeClere and B. Bartel</span>", '/abrc/bartel.jsp', '_new'],
["<span title=\"\">T-DNA lines from Csaba Koncz</span>", '/abrc/koncz.jsp', '_new'],
],
["<span title=\"Find scientific articles and abstracts about Arabidopsis. Find techniques and methods for Arabidopsis and molecular biology.\">Literature, References and Protocols</span>", null, null,
["<span title=\"The AIS newsletter was published from 1964-1990 and contains brief reports of Arabidopsis Research.\">The Electronic Arabidopsis Information Service</span>", '/ais/newaishint.html', '_new'],
["<span title=\"Weeds World is an electronic journal of Arabidopsis Research that was published from 1994-1997. The archived contents can be found in this directory.\">Weeds World</span>", '/ww/home.html', '_new'],
["<span title=\"Search Arabidopsis and molecular biology protocols in TAIR by title, author and description or browse by keyword.\">TAIR Protocol Search</span>", '/servlets/Search?action=new_search&type=protocol', '_new'],
["<span title=\"Find Arabidopsis papers and electronic articles about Arabidopsis research. Search and view abstracts from past Arabidopsis meetings.\">Publication Search</span>", '/servlets/Search?action=new_search&type=publication', '_new'],
["<span title=\"Find genes, annotations, publications and microarray experiments by keyword. Browse the ontologies to find groups of similar genes, etc...\">Keyword Search and Browse</span>", '/servlets/Search?action=new_search&type=keyword', '_new'],
["<span title=\"Laboratory protocols and techniques for Arabidopsis researcherss.\">TAIR Lab Protocols</span>", '/info/protocols.jsp', '_new'],
["<span title=\"Browse or search using keywords to find genes, microarray experiments,papers and annotations.\">Keyword Search and Browse</span>", '/jsp/search/keyword_form.jsp', '_new'],
["<span title=\"Links to electronic versions of Weeds World and The Arabidopsis Information Resource.\">Electronic Arabidopsis Journals</span>", '/browse/electricarab.jsp', '_new'],
["<span title=\"Access to the online version of the Compleat Guide to Arabidopsis: an anthology of protocols compiled by Caroline Dean and Dave Flanders.\">TAIR About the Compleat Guide</span>", '/info/newcomguide.jsp', '_new'],
["<span title=\"How to make and analyze enhancer traps and gene traps.\">TAIR Enhancer and Gene Trap Transposon Mutagenesis in Arabidopsis</span>", '/info/springer.jsp', '_new'],
["<span title=\"Links to journals of interest to plant researchers.\">Plant Journals</span>", '/links/plantjournals.jsp', '_new'],
["<span title=\"Browse the contents of the on line Arabidopsis Information Service.\">Electronic Arabidopsis Information Service Reports</span>", '/ais/newaishint.html', '_new'],
["<span title=\"Browse the contents of the on line publication Weeds World.\">Weeds World</span>", '/ww/home.html', '_new'],
["<span title=\"Methods and techniques for Arabidopsis Research from a variety of sources. Portable document format (PDFs) can be downloaded and viewed using Adobe Acrobat Reader.\">Arabidopsis Protocols Folder</span>", 'ftp://ftp.arabidopsis.org/home/tair/Protocols', '_new'],
["<span title=\"Laboratory manual written to accompany the EMBO practical course in Arabidopsis , 1996.\">EMBO Arabidopsis Course manual</span>", 'ftp://ftp.arabidopsis.org/home/tair/Protocols/EMBOmanual', '_new'],
["<span title=\"Teacher Handbook for the Plant Research and Education Partnership from Fralin Institute\">PREP Handbook</span>", 'ftp://ftp.arabidopsis.org/home/tair/Protocols/PREP_handbook', '_new'],
["<span title=\"All Arabidopsis protocols from the Compleat Guide in PDF format.\">Arabidopsis Compleat Guide </span>", 'ftp://ftp.arabidopsis.org/home/tair/Protocols/compleat_guide/comguidePDFs', '_new'],
],
["<span title=\"Find information about Arabidopsis metabolic pathways including reactions,enzymes and compounds.\">Metabolic Pathways</span>", null, null,
["<span title=\"AraCyc is a database of Arabidopsis pathways. Pathways can be searched by compounds, reactions, genes, enzymes,proteins and pathways. The graphical interface can be used to view and browse pathways down to the level of individual reactions. The Expression Viewer can be used to overlay gene expression data to find pathways that are up or down regulated.\">TAIR Biochemical Pathways</span>", '/tools/aracyc/index.jsp', '_new'],
],
["<span title=\"News and upcoming events of interest to plant biologist. Job opportunities in academic labs.\">News,Events and Job Postings</span>", null, null,
["<span title=\"\">News,conferences and newsgroups</span>", '/news/index.jsp', '_new'],
["<span title=\"Search, browse and read postings from the Arabidopsis community newsgroup. Register to post on the newsgroup.\">TAIR Arabidopsis Newsgroup</span>", '/news/newsgroup.jsp', '_new'],
["<span title=\"Find information about upcoming meetings and conferences.\">Conferences and Events</span>", '/news/events.jsp', '_new'],
["<span title=\"Find jobs and post job openings at TAIR.\">TAIR Community Jobs</span>", '/news/jobs.jsp', '_new'],
],
["<span title=\"Find researchers and laboratories.\">People and Labs</span>", null, null,
["<span title=\"Find Arabidopsis researchers and labs. Search by personal or organization name, location and keyword. Find colleagues with similar or shared interests. \">Community Search</span>", '/servlets/Search?type=community&action=new_search', '_new'],
["<span title=\"Information about and resources from US and International Functional Genomics projects.\">Arabidopsis 2010 projects</span>", '/info/2010_projects/index.jsp', '_new'],
["<span title=\"Browse lists of research labs working on Arabidopsis\">Arabidopsis Labs</span>", '/info/lab.jsp', '_new'],
["<span title=\"Links to information about individual US and International Functional genomics projects.\">Projects in Functional Genomics of Arabidopsis Genes</span>", '/info/2010_projects/projects.jsp', '_new'],
["<span title=\"Compilation of links to resources being developed for Arabidopsis research.\">List of Resources for Arabidopsis Research</span>", '/info/2010_projects/Resources.jsp', '_new'],
["<span title=\"\">TAIR help Community Registration</span>", '/help/helppages/commreg.jsp', '_new'],
],
["<span title=\"Find and Analyze Arabidopsis proteins.\">Protein Resources</span>", null, null,
["<span title=\"Find individual proteins or sets of proteins having similar characteristics. Search by name, physiochemical attributes,domains, structural classification and location.\">Protein Search</span>", '/servlets/Search?type=protein&action=new_search', '_new'],
["<span title=\"Download lists of proteins by physico-chemical characteristics, structural class,domain and subcellular localization.\">TAIR Bulk Protein Download</span>", '/tools/bulk/protein/index.jsp', '_new'],
["<span title=\"Links to external proteomics databases and tools for analyzing protein structure and function.\">Proteome Resources</span>", '/links/proteome.jsp', '_new'],
],
["<span title=\"Advanced Searching of TAIR database.\">Search TAIR</span>", null, null,
["<span title=\"Use for searching TAIR database by name or keyword.\">TAIR General Search</span>", '/servlets/Search?type=general&action=new_search', '_new'],
["<span title=\"Find genetic markers for mapping or following linked genes. Search by name,type, and location. Can be used to find markers polymorphic between selected ecotypes.\">Genetic Marker Search</span>", '/servlets/Search?type=marker&action=new_search', '_new'],
["<span title=\"Find individual proteins or sets of proteins having similar characteristics. Search by name, physiochemical attributes,domains, structural classification and location.\">Protein Search</span>", '/servlets/Search?type=protein&action=new_search', '_new'],
["<span title=\"Find genes by name, keyword,type and location.\">Gene Search</span>", '/servlets/Search?type=gene&action=new_search', '_new'],
["<span title=\"Find mutants, T-DNA/Transposon insertion lines, mapping populations and natural variants of Arabidopsis. Search by name, type, genotype,construct and more.\">Germplasm Search</span>", '/servlets/Search?action=new_search&type=germplasm', '_new'],
["<span title=\"Search Arabidopsis and molecular biology protocols in TAIR by title, author and description or browse by keyword.\">TAIR Protocol Search</span>", '/servlets/Search?action=new_search&type=protocol', '_new'],
["<span title=\"Find natural variants of Arabidopsis and other species. Search by name, stock number and collection site data such as country.\">Ecotype Search</span>", '/servlets/Search?action=new_search&type=ecotype', '_new'],
["<span title=\"Find mutant alleles, T-DNA and transposon insertions, transgenes, SNPs, INDELS and other polymorphisms. Search by name, type, location. Search can be limited to find polymorphisms for specific ecotypes.\">Polymorphism/Allele Search</span>", '/servlets/Search?action=new_search&type=polyallele', '_new'],
["<span title=\"Find Arabidopsis researchers and labs. Search by personal or organization name, location and keyword. Find colleagues with similar or shared interests. \">Community Search</span>", '/servlets/Search?type=community&action=new_search', '_new'],
["<span title=\"Find Arabidopsis papers and electronic articles about Arabidopsis research. Search and view abstracts from past Arabidopsis meetings.\">Publication Search</span>", '/servlets/Search?action=new_search&type=publication', '_new'],
["<span title=\"Find genes, annotations, publications and microarray experiments by keyword. Browse the ontologies to find groups of similar genes, etc...\">Keyword Search and Browse</span>", '/servlets/Search?action=new_search&type=keyword', '_new'],
["<span title=\"Find the history of revisions such as splits and merges of genes. Upload a file, type or paste in AGI locus identifiers and obtain a downloadable list of all changes made to each locus.\">Locus History Search</span>", '/tools/bulk/locushistory/index.jsp', '_new'],
["<span title=\"Find what genes are arrayed on AFGC and Affymetrix chips. View spot history for AFGC array elements and clustered data from across all AFGC experiments. Download lists of mappings between genes and array elements.\">Microarray Elements Search and Download</span>", '/tools/bulk/microarray/index.jsp', '_new'],
["<span title=\"Find and Download Data from Arabidopsis microarray experiments. Search by keywords, experiment name and researcher name.\">Microarray Experiments Search</span>", '/servlets/Search?type=expr&search_action=new_search', '_new'],
["<span title=\"Find expression data for a gene or set of genes using locus identifiers or microarray element names. Select cut off values for expression or limit to only specific array technologies.\">Expression Search</span>", '/servlets/Search?action=new_search&type=expression', '_new'],
["<span title=\"Find microarray experiment data in TAIR and download raw data.\">Microarray Expression Search</span>", '/jsp/search/expression_form.jsp', '_new'],
["<span title=\"Browse or search using keywords to find genes, microarray experiments,papers and annotations.\">Keyword Search and Browse</span>", '/jsp/search/keyword_form.jsp', '_new'],
],
["<span title=\"Search and Browse DNA and Seed Stocks from ABRC\">Seed and DNA Stocks</span>", null, null,
["<span title=\"\">ABRC TAIR Home Page</span>", '/abrc/index.jsp', '_new'],
["<span title=\"Search for clones, vectors, libraries,pooled genomic DNA and filters. Find DNA Stocks to order from the ABRC.\">DNA Search</span>", '/servlets/Search?action=new_search&type=dna', '_new'],
["<span title=\"Find mutants, T-DNA/Transposon insertion lines, mapping populations and natural variants of Arabidopsis. Search by name, type, genotype,construct and more.\">Germplasm Search</span>", '/servlets/Search?action=new_search&type=germplasm', '_new'],
["<span title=\"Find natural variants of Arabidopsis and other species. Search by name, stock number and collection site data such as country.\">Ecotype Search</span>", '/servlets/Search?action=new_search&type=ecotype', '_new'],
["<span title=\"Browse ABRC Seed and DNA stocks\">ABRC Stock Catalog</span>", '/servlets/Order?state=catalog', '_new'],
["<span title=\"Find mutant alleles, T-DNA and transposon insertions, transgenes, SNPs, INDELS and other polymorphisms. Search by name, type, location. Search can be limited to find polymorphisms for specific ecotypes.\">Polymorphism/Allele Search</span>", '/servlets/Search?action=new_search&type=polyallele', '_new'],
["<span title=\"How ABRC user fees are calculated\">TAIR ABRC User Fee System</span>", '/abrc/fees.jsp', '_new'],
["<span title=\"Information about Salk T-DNA insertion line stocks.\">Sequence-indexed T-DNA Lines donated by J. Ecker</span>", '/abrc/ecker_flank.jsp', '_new'],
["<span title=\"\">Cold Spring Harbor Enhancer Trap and Gene Trap Lines</span>", '/abrc/cshl_gtet.jsp', '_new'],
["<span title=\"\">T-DNA Seed Pools and Lines available at ABRC</span>", '/abrc/tdna_lines.jsp', '_new'],
["<span title=\"T-DNA insertion lines from the Arabidopsis Knockout Facility\">AKF seed pools donated to ABRC</span>", '/abrc/akf.jsp', '_new'],
["<span title=\"Ds transposon insertion lines from the Institute for Molecular Agrobiology.\">Institute for Molecular Agrobiology (IMA)lines donated to ABRC</span>", '/abrc/ima.jsp', '_new'],
["<span title=\"How to obtain Targeted Local Induced Lesion lines.\">Tilling lines from Henikoff and Comai labs</span>", '/abrc/henikoff.jsp', '_new'],
["<span title=\"\">Recombinant inbred mapping lines from ABRC</span>", '/abrc/ri_mapping.jsp', '_new'],
["<span title=\"\">Enhancer Trap Lines from Scott Poethig</span>", '/abrc/poethig.jsp', '_new'],
["<span title=\"\">ABRC collection of Brassica seed stocks</span>", '/abrc/brassica.jsp', '_new'],
["<span title=\"\">ESTs from MSU and CNRS</span>", '/abrc/ests.jsp', '_new'],
["<span title=\"\">Immature Seed ESTs donated to ABRC by Christoph Benning</span>", '/abrc/benningests.jsp', '_new'],
["<span title=\"\">ABRC Libraries and clones from libraries</span>", '/abrc/libraries.jsp', '_new'],
["<span title=\"\">Full length cDNA clones from the SSP Consortium.</span>", '/abrc/ssp_clone.jsp', '_new'],
["<span title=\"\">Pooled DNA</span>", '/abrc/pooled_dna.jsp', '_new'],
["<span title=\"\">ABRC Payment</span>", '/abrc/payment.jsp', '_new'],
["<span title=\"\">ABRC Advisory Committee</span>", '/abrc/advis_comm.jsp', '_new'],
["<span title=\"\">ABRC Stock Acquisition/Deacquisition Policy</span>", '/abrc/acquis_deacquis.jsp', '_new'],
["<span title=\"Information about Arabidopsis full length cDNA clones from RIKEN BioResource Center.\">RAFL Full Length cDNAs from RIKEN</span>", '/links/riken.jsp', '_new'],
["<span title=\"Links to sources of seed stocks for finding mutants in your favorite genes. This includes sources not available from the major stock centers.\">List of Reverse Genetics Seed Stock Resources</span>", '/info/2010_projects/Reverse_Genetic_Stocks.jsp', '_new'],
["<span title=\"Information about how T-DNA lines donated by Ken Feldmann were generated and how to order them from ABRC.\">T-DNA lines from Ken Feldmann</span>", '/abrc/feldmann.jsp', '_new'],
["<span title=\"Information about how to order T-DNA lines donated by Tom Jack and how they were generated.\">T-DNA lines from T. Jack</span>", '/abrc/jack.jsp', '_new'],
["<span title=\"How to order T-DNA lines from INRA and how they were made.\">T-DNA lines from INRA</span>", '/abrc/inra.jsp', '_new'],
["<span title=\"How to order T-DNA lines donate by Detlef Weigel and how they were generated.\">T-DNA lines from Detlef Weigel</span>", '/abrc/weigel.jsp', '_new'],
["<span title=\"How to order T-DNA lines from Alonso and Crosby and how they were generated.\">T-DNA Transformed Lines donated by J. Alonso, W. Crosby and</span>", '/abrc/alonso.jsp', '_new'],
["<span title=\"How to order activation tag lines from Scheible and Somerville and how they were generated.\">T-DNA Transformed Activation Tag lines from W. Scheible and C. Somerville</span>", '/abrc/Scheible.jsp', '_new'],
["<span title=\"How to order T-DNA insertion lines donated by Sussman and Amasino and how they were generated.\">T-DNA lines from M. Sussman and R. Amasino</span>", '/abrc/sussman_fwd.jsp', '_new'],
["<span title=\"\">T-DNA lines from R. Bressan and S. Yokoi</span>", '/abrc/bressan.jsp', '_new'],
["<span title=\"\">T-DNA Lines donated by S. LeClere and B. Bartel</span>", '/abrc/bartel.jsp', '_new'],
["<span title=\"\">T-DNA lines from Csaba Koncz</span>", '/abrc/koncz.jsp', '_new'],
["<span title=\"\">GFP lines from Jim Haseloff</span>", '/abrc/haseloff.jsp', '_new'],
["<span title=\"\">Promoter Trap lines from Patrick Gallois</span>", '/abrc/gallois.jsp', '_new'],
["<span title=\"Random GFP cDNA fusion transformants for sub cellular protein localization.\">Random GFP cDNA Fusion T-DNA Transformants from David Ehrhardt</span>", '/abrc/ehrhardt_gfp.jsp', '_new'],
["<span title=\"Launch pad lines for transposon tagging in Arabidopsis\">Ds Launch Pad lines from P. Muskett</span>", '/abrc/muskett_launchpad.jsp', '_new'],
["<span title=\"Col X Ler recombinant inbred population\">Recombinant Inbred lines from C. Lister and C. Dean</span>", '/abrc/dean_ri.jsp', '_new'],
["<span title=\"Ler X CVi recombinant inbred population\">Recombinant Inbred Lines from M. Koornneef and C. Alonso-Blanco</span>", '/abrc/koornneef_ri.jsp', '_new'],
["<span title=\"Col-3 or Col-5 X Nd-1 recombinant inbred population\">RI lines donated by E. Holub, J. Beynon and I. Crute</span>", '/abrc/holub_beynon_crute.jsp', '_new'],
["<span title=\"ColXKas-1 recombinant inbred population\">Recombinant Inbred Lines from S. Somerville</span>", '/abrc/somerville_ri.jsp', '_new'],
["<span title=\"Bay-0 x Shahdara recombinant inbred population.\">Recombinant Inbred lines from Loudet and Chaillou.</span>", '/abrc/Loudet_Chaillou_ri.jsp', '_new'],
["<span title=\"Mapping population with dominant T-DNA linked markers.\">Marker Lines with Mapped T-DNA Insertions from Dr. Mieke van Lijsebettens</span>", '/abrc/vanlijsebettens.jsp', '_new'],
["<span title=\"L(er)X Col mapping population in qrt mutant background for tetrad analysis.\">Tetrad Mapping Population donated by D. Preuss and G. Copenhaver</span>", '/abrc/preuss.jsp', '_new'],
],
["<span title=\"Data submission forms for sending data to TAIR.\">Submit Data</span>", null, null,
["<span title=\"How to submit microarray data to TAIR database\">Guidelines for Submitting Microarray Data</span>", '/submit/microarray.submission.jsp', '_new'],
["<span title=\"\">TAIR Help Updating Publications</span>", '/help/helppages/addpub.jsp', '_new'],
["<span title=\"Instructions and forms for submitting data to TAIR.\">TAIR and ABRC Data Submission</span>", '/submit/index.jsp', '_new'],
["<span title=\"Guidelines and submission forms for submitting microarray experiment data to TAIR.\">Guidelines for Submitting Microarray Experiment Data</span>", '/info/microarray_experiment.jsp', '_new'],
["<span title=\"Guidelines and submission forms for submitting data about array designs (chip information) to TAIR.\">Array Design Submission</span>", '/submit/array_submission.jsp', '_new'],
["<span title=\"Guidelines for gene naming in Arabidopsis.\">Arabidopsis nomenclature</span>", '/info/guidelines.jsp', '_new'],
["<span title=\"Guidelines and forms for submitting gene family data to TAIR.\">Gene Family Data Submission</span>", '/submit/genefamily_submission.jsp', '_new'],
["<span title=\"Guidelines for submitting lists of genes being studied as part of a US or international functional genomics project.\">Submitting 2010 Genes</span>", '/info/2010_projects/submit_2010.jsp', '_new'],
["<span title=\"Guidelines and forms for submitting corrections and new gene structures to TAIR.\">Gene Structural Annotation Guidelines for Submitting Data</span>", '/submit/gene_annotation.submission.jsp', '_new'],
["<span title=\"Guidelines and forms for submitting functional annotations to TAIR.\">Gene Functional Annotation Guidelines for Submitting Data</span>", '/submit/functional_annotation.submission.jsp', '_new'],
["<span title=\"Guidelines and forms for submitting marker data to TAIR.\">Submission of bulk marker data to TAIR</span>", '/submit/marker_submission.jsp', '_new'],
["<span title=\"Guidelines and forms for submitting experiment data for microarrays to TAIR.\">Guidelines for Submitting Microarray Experiment Data-Experiment Info </span>", '/info/microarray_experiment_info.jsp', '_new'],
["<span title=\"Guidelines for submitting data on replicate hybridizations for submitting microarray data to TAIR.\">Guidelines for Submitting Microarray Experiment Data- Replicates </span>", '/info/microarray_experiment_replicate.jsp', '_new'],
["<span title=\"Guidelines for submitting RNA sample data for microarray data submission to TAIR.\">Guidelines for Submitting Microarray Experiment Data-Sample Info </span>", '/info/microarray_experiment_rna.jsp', '_new'],
["<span title=\"Guidelines for submitting information about hybridizations associated to a microarray experiment submission at TAIR.\">Guidelines for Submitting Microarray Experiment Data-Hybridization Info</span>", '/info/microarray_experiment_hybrid.jsp', '_new'],
["<span title=\"\">Guidelines for Submitting Microarray Experiment Data-Results</span>", '/info/microarray_experiment_results.jsp', '_new'],
["<span title=\"\">TAIR Help Adding Comments</span>", '/help/helppages/addcomment.jsp', '_new'],
],
["<span title=\"TAIR provides access to integrated information about Arabidopsis thaliana including its genome, gene expression, genetic resources and research community.\">TAIR Home page</span>", '/index.jsp', '_new'],
],
];